# Generated by Django 3.0.5 on 2020-04-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_reviews_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='destination',
            field=models.CharField(default='Kolkata', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
