# Generated by Django 3.0.5 on 2020-04-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_auto_20200418_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='destination',
            field=models.CharField(default='Kolkata', max_length=200),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
