# Generated by Django 3.0.5 on 2020-04-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0008_auto_20200418_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='arriveson',
            field=models.DateField(default=-2004),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='departson',
            field=models.DateField(default=-2005),
            preserve_default=False,
        ),
    ]
