# Generated by Django 3.0.5 on 2020-04-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0011_auto_20200419_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('cart', models.IntegerField(default=0)),
                ('destination', models.CharField(default='Kolkata', max_length=200)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('destination', models.CharField(default='Hrishikesh', max_length=200)),
                ('review', models.TextField()),
                ('heading', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Destinations',
            new_name='Destination',
        ),
    ]
